# test config AB test, no waveform, 3 conditions, no looping


testname: ABX without looping and waveform
testId: abx_noloop_nowav
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:

    - type: paired_comparison
      id: trialAB2
      name: Mono Trial AB
      unforced: I don't know
      content: test description AB
      showWaveform: false
      enableLooping: false 
      reference: configs/resources/audio/mono_ref.wav
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav


    - type: finish
      name: Thank you
      content: Thank you for attending
      showResults: true
      writeResults: true
