# Likert single stimulus page 3 stimuli, 2 responses


testname: Likert Single Simulus with two responses
testId: lss_2scale
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php



pages:

    - type: likert_single_stimulus
      id: lss1
      name: likert
      content: test description
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav
      response:
        - value: not at all
          label: Not at all
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: not a lot
          label: Not a lot
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png


    - type: finish
      name: Thank you
      content: Thank you for attending
      showResults: true
      writeResults: true
